menu:
    Blog: /
    GitHub: https://github.com/Tecur
    Archive: archives/
    Feed: atom.xml

favicon: favicon.svg
logo: favicon.svg

# Comment
# e.g disqus: claymcleod 
disqus:

# Analytics
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2022

# Image Credits
enable_image_credit: true